module.exports = {
    type: {
        RESIDENTIAL: "RESIDENTIAL",
        COMMERCIAL: "COMMERCIAL",
        INDUSTRIAL: "INDUSTRIAL",
        AGRICULTURAL: "AGRICULTURAL",
    },
    subtype: {
        FLAT: "FLAT",
        INDEPENDENT_HOUSE: "INDEPENDENT HOUSE",
        PLOT: "PLOT",
        FLOOR: "FLOOR",
        VILLA: "VILLA",
        DUPLEX: "DUPLEX",
        STUDIO_APARTMENT: "STUDIO APARTMENT",
        SERVICE_APARTMENT: "SERVICE APARTMENT",
        FARM_HOUSE: "FARM HOUSE",
        COMMERCIAL_SHOP: "COMMERCIAL SHOP",
        COMMERCIAL_PLOT: "COMMERCIAL PLOT",
        COMMERCIAL_SCO: "COMMERCIAL SCO",
        COMMERCIAL_SPACE: "COMMERCIAL SPACE",
        AGRICULTURAL_LAND: "AGRICULTURAL LAND",
        OTHER: "OTHER",
    },
    status: {
        PENDING: "PENDING",
        REJECTED: "REJECTED",
        LIVE: "LIVE",
        DELETED: "DELETED",
        SOLD: "SOLD"
    }
}